use_frameworks!

target 'DBDebugToolkit_Example' do
  pod 'DBDebugToolkit', :path => '../'

  target 'DBDebugToolkit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
